apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  annotations:
    installer.open-cluster-management.io/mce-subscription-spec: '{"name": "multicluster-engine"}'
  name: multiclusterhub
spec:
  imagePullSecret: multiclusterhub-operator-pull-secret
  
